[package]
name = "rough"
version = "0.1.9"
edition = "2021"

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
eval = "0.4.3"
gtk = "0.15.5"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
